version: '3'
services:
  rpc-server:
    ports:
      - "8000:8000"
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    volumes:
      - ".:/usr/src/app"
    command: >
      /bin/sh -c "pip install Pillow && python server.py"
